### ISSUE TITLE
Migration to new Webhook Architecture

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub-webhook#1]
As discussed in yesterdays meeting these are the steps we have to complete before we can do the full migration

- [x] Setup two VMs with Ubuntu
  - [x]  Test VM
  - [x] Production VM
- [x] install necessary software (maybe via Ansible?)
  - [x] Docker
  - [x] Sysbox
  - [x] skohub webhook
- [x] backup dist folder from current skohub-vocabs repo and copy to webhook repo
- [x] adjust .env (use `webhook` as docker tag as long as the PR in skohub-vocabs is not merged)
- [x] start new webhook service (manual or via ansible?)
- [x] adjust web proxy settings to point to new VM

**Comment by Phu2** [comment]
After triggering a build (using curl instead of a Github action) an error occurred:
```
[...]
skohub-webhook-webhook-1  | Build Finish
skohub-webhook-webhook-1  | Build triggered
skohub-webhook-webhook-1  | Processing
skohub-webhook-webhook-1  | Created file: hcrt.ttl
skohub-webhook-webhook-1  | Created file: hochschulfaechersystematik.ttl
skohub-webhook-webhook-1  | gatsbyError: docker: Error response from daemon: error creating overlay mount to /var/lib/docker/overlay2/761516c953e1358f497b1dab6e640d011f1da368bad5887bb01f8bb42c2f5ccb-init/merged: function not implemented.
skohub-webhook-webhook-1  | See 'docker run --help'.
[...]
``` 
Looks like the root filesystem of the vocabs container cannot be established.
This is new and has not been encountered before. Re-deploy using ansible helps (pulling the image again).
