### ISSUE TITLE
Add a log about current built vocabularies

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub-webhook#5]
We should add a log that gives information about what vocabularies are currently being built and served.

**Comment by acka47** [comment]
Maybe related to https://github.com/skohub-io/skohub-vocabs/issues/231

**Comment by sroertgen** [comment]
This should also contain the info about rebuilt or removed vocabularies 

Related #21

**Comment by sroertgen** [comment]
Log should also contain a timestamp
