### ISSUE TITLE
Vocabs in folders not published

### ISSUE THREAD

**Issue by literarymachine** [skohub-io/skohub-webhook#6]
> What is strange, though, is that the vocabs in folders /nwbib and /rpb aren't published, compare https://test.skohub.io/hbz/lobid-vocabs/heads/master/ & https://github.com/hbz/lobid-vocabs. Or do I just don't find them?

https://github.com/hbz/skohub-vocabs/pull/74#issuecomment-603441293

**Comment by sroertgen** [comment]
The issue seems to be that folders are not recursively parsed for files.
